In [1]:
#주제선정 -> 데이터수집(파일의 형태로 담겨서 제공되어질 것임) 
# -> 파일에 있는 데이터를 읽어와서 처리할 때 어떻게 처리하면 되는지에 대한 실습
import tensorflow as tf
import numpy as np

In [2]:
data = np.loadtxt('../data/data-01-test-score.csv', delimiter=',', dtype=np.float32) 
#테이블 형태로 데이터가 저장만 되어져 있다면 다 읽어올 수 있음 / delimiter:구분자의 의미를 가진 파라메타

x_data = data[:, 0:-1]
y_data = data[:, [-1]] #마지막 항목만 지정하려면 리스트로 -1을 지정하도록 한다.
#선형회귀는 대표적인 지도학습임. 따라서 정답으로 사용할 데이터를 분리시키도록 한다.

In [3]:
print(x_data, '\nx_data shape:', x_data.shape)
print(y_data, '\ny_data shape:', y_data.shape)
#리스트형태로 데이터를 반환해주고 있음.

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape: (25, 3)
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 
y_data shape: (25, 1)


In [4]:
tf.model = tf.keras.Sequential()

tf.model.add(tf.keras.layers.Dense(input_dim=3, units=1, activation='linear')) #가장 선호하는 코드(가독성도 높이고 간단하게 작업할 수 있는 코드) 
#input_dim:입력데이터 핏쳐 갯수, units:출력데이터 핏쳐 갯수 
#tf.model.add(tf.keras.layers.Activation('linear')) 가독성을 위해 붙인 것임

In [5]:
tf.model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 4         
                                                                 
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________


In [6]:
tf.model.compile(loss='mse', optimizer=tf.keras.optimizers.SGD(learning_rate=1e-5)) #learning_rate는 디폴트가 0.1부터임

In [7]:
tf.model.fit(x_data, y_data, epochs=2000) 
#learning_rate의 값을 작게 넣으면 최저점까지 도달할 수 있도록 학습값을 높게 잡아줘야 함

Epoch 1/2000
1/1 [==============================] - 0s 465ms/step - loss: 1428.4637
Epoch 2/2000
1/1 [==============================] - 0s 3ms/step - loss: 533.4522
Epoch 3/2000
1/1 [==============================] - 0s 0s/step - loss: 202.5403
Epoch 4/2000
1/1 [==============================] - 0s 0s/step - loss: 80.1917
Epoch 5/2000
1/1 [==============================] - 0s 0s/step - loss: 34.9549
Epoch 6/2000
1/1 [==============================] - 0s 0s/step - loss: 18.2282
Epoch 7/2000
1/1 [==============================] - 0s 0s/step - loss: 12.0426
Epoch 8/2000
1/1 [==============================] - 0s 816us/step - loss: 9.7543
Epoch 9/2000
1/1 [==============================] - 0s 0s/step - loss: 8.9070
Epoch 10/2000
1/1 [==============================] - 0s 0s/step - loss: 8.5924
Epoch 11/2000
1/1 [==============================] - 0s 0s/step - loss: 8.4748
Epoch 12/2000
1/1 [==============================] - 0s 0s/step - loss: 8.4300
Epoch 13/2000
1/1 [========================

1/1 [==============================] - 0s 0s/step - loss: 8.2240
Epoch 105/2000
1/1 [==============================] - 0s 0s/step - loss: 8.2221
Epoch 106/2000
1/1 [==============================] - 0s 0s/step - loss: 8.2202
Epoch 107/2000
1/1 [==============================] - 0s 0s/step - loss: 8.2183
Epoch 108/2000
1/1 [==============================] - 0s 16ms/step - loss: 8.2164
Epoch 109/2000
1/1 [==============================] - 0s 0s/step - loss: 8.2145
Epoch 110/2000
1/1 [==============================] - 0s 0s/step - loss: 8.2127
Epoch 111/2000
1/1 [==============================] - 0s 0s/step - loss: 8.2108
Epoch 112/2000
1/1 [==============================] - 0s 0s/step - loss: 8.2089
Epoch 113/2000
1/1 [==============================] - 0s 0s/step - loss: 8.2070
Epoch 114/2000
1/1 [==============================] - 0s 16ms/step - loss: 8.2052
Epoch 115/2000
1/1 [==============================] - 0s 0s/step - loss: 8.2033
Epoch 116/2000
1/1 [==============================]

1/1 [==============================] - 0s 0s/step - loss: 8.0399
Epoch 207/2000
1/1 [==============================] - 0s 0s/step - loss: 8.0381
Epoch 208/2000
1/1 [==============================] - 0s 17ms/step - loss: 8.0364
Epoch 209/2000
1/1 [==============================] - 0s 0s/step - loss: 8.0347
Epoch 210/2000
1/1 [==============================] - 0s 0s/step - loss: 8.0330
Epoch 211/2000
1/1 [==============================] - 0s 0s/step - loss: 8.0312
Epoch 212/2000
1/1 [==============================] - 0s 0s/step - loss: 8.0296
Epoch 213/2000
1/1 [==============================] - 0s 0s/step - loss: 8.0278
Epoch 214/2000
1/1 [==============================] - 0s 17ms/step - loss: 8.0261
Epoch 215/2000
1/1 [==============================] - 0s 0s/step - loss: 8.0244
Epoch 216/2000
1/1 [==============================] - 0s 808us/step - loss: 8.0227
Epoch 217/2000
1/1 [==============================] - 0s 0s/step - loss: 8.0210
Epoch 218/2000
1/1 [============================

Epoch 308/2000
1/1 [==============================] - 0s 0s/step - loss: 7.8717
Epoch 309/2000
1/1 [==============================] - 0s 0s/step - loss: 7.8701
Epoch 310/2000
1/1 [==============================] - 0s 17ms/step - loss: 7.8686
Epoch 311/2000
1/1 [==============================] - 0s 0s/step - loss: 7.8670
Epoch 312/2000
1/1 [==============================] - 0s 0s/step - loss: 7.8654
Epoch 313/2000
1/1 [==============================] - 0s 0s/step - loss: 7.8639
Epoch 314/2000
1/1 [==============================] - 0s 0s/step - loss: 7.8623
Epoch 315/2000
1/1 [==============================] - 0s 0s/step - loss: 7.8607
Epoch 316/2000
1/1 [==============================] - 0s 432us/step - loss: 7.8592
Epoch 317/2000
1/1 [==============================] - 0s 0s/step - loss: 7.8576
Epoch 318/2000
1/1 [==============================] - 0s 0s/step - loss: 7.8560
Epoch 319/2000
1/1 [==============================] - 0s 0s/step - loss: 7.8545
Epoch 320/2000
1/1 [===============

Epoch 410/2000
1/1 [==============================] - 0s 0s/step - loss: 7.7181
Epoch 411/2000
1/1 [==============================] - 0s 0s/step - loss: 7.7167
Epoch 412/2000
1/1 [==============================] - 0s 0s/step - loss: 7.7153
Epoch 413/2000
1/1 [==============================] - 0s 0s/step - loss: 7.7138
Epoch 414/2000
1/1 [==============================] - 0s 0s/step - loss: 7.7124
Epoch 415/2000
1/1 [==============================] - 0s 17ms/step - loss: 7.7110
Epoch 416/2000
1/1 [==============================] - 0s 0s/step - loss: 7.7095
Epoch 417/2000
1/1 [==============================] - 0s 0s/step - loss: 7.7081
Epoch 418/2000
1/1 [==============================] - 0s 0s/step - loss: 7.7067
Epoch 419/2000
1/1 [==============================] - 0s 0s/step - loss: 7.7052
Epoch 420/2000
1/1 [==============================] - 0s 0s/step - loss: 7.7038
Epoch 421/2000
1/1 [==============================] - 0s 17ms/step - loss: 7.7024
Epoch 422/2000
1/1 [================

1/1 [==============================] - 0s 0s/step - loss: 7.5792
Epoch 512/2000
1/1 [==============================] - 0s 0s/step - loss: 7.5779
Epoch 513/2000
1/1 [==============================] - 0s 0s/step - loss: 7.5766
Epoch 514/2000
1/1 [==============================] - 0s 0s/step - loss: 7.5753
Epoch 515/2000
1/1 [==============================] - 0s 16ms/step - loss: 7.5740
Epoch 516/2000
1/1 [==============================] - 0s 0s/step - loss: 7.5726
Epoch 517/2000
1/1 [==============================] - 0s 0s/step - loss: 7.5713
Epoch 518/2000
1/1 [==============================] - 0s 0s/step - loss: 7.5700
Epoch 519/2000
1/1 [==============================] - 0s 0s/step - loss: 7.5687
Epoch 520/2000
1/1 [==============================] - 0s 0s/step - loss: 7.5674
Epoch 521/2000
1/1 [==============================] - 0s 16ms/step - loss: 7.5661
Epoch 522/2000
1/1 [==============================] - 0s 0s/step - loss: 7.5648
Epoch 523/2000
1/1 [==============================]

1/1 [==============================] - 0s 0s/step - loss: 7.4510
Epoch 614/2000
1/1 [==============================] - 0s 17ms/step - loss: 7.4498
Epoch 615/2000
1/1 [==============================] - 0s 0s/step - loss: 7.4486
Epoch 616/2000
1/1 [==============================] - 0s 0s/step - loss: 7.4474
Epoch 617/2000
1/1 [==============================] - 0s 0s/step - loss: 7.4462
Epoch 618/2000
1/1 [==============================] - 0s 0s/step - loss: 7.4450
Epoch 619/2000
1/1 [==============================] - 0s 0s/step - loss: 7.4438
Epoch 620/2000
1/1 [==============================] - 0s 17ms/step - loss: 7.4426
Epoch 621/2000
1/1 [==============================] - 0s 0s/step - loss: 7.4414
Epoch 622/2000
1/1 [==============================] - 0s 0s/step - loss: 7.4402
Epoch 623/2000
1/1 [==============================] - 0s 0s/step - loss: 7.4390
Epoch 624/2000
1/1 [==============================] - 0s 0s/step - loss: 7.4378
Epoch 625/2000
1/1 [==============================]

1/1 [==============================] - 0s 17ms/step - loss: 7.3339
Epoch 716/2000
1/1 [==============================] - 0s 0s/step - loss: 7.3328
Epoch 717/2000
1/1 [==============================] - 0s 0s/step - loss: 7.3317
Epoch 718/2000
1/1 [==============================] - 0s 0s/step - loss: 7.3306
Epoch 719/2000
1/1 [==============================] - 0s 0s/step - loss: 7.3295
Epoch 720/2000
1/1 [==============================] - 0s 0s/step - loss: 7.3284
Epoch 721/2000
1/1 [==============================] - 0s 17ms/step - loss: 7.3273
Epoch 722/2000
1/1 [==============================] - 0s 0s/step - loss: 7.3262
Epoch 723/2000
1/1 [==============================] - 0s 0s/step - loss: 7.3251
Epoch 724/2000
1/1 [==============================] - 0s 0s/step - loss: 7.3240
Epoch 725/2000
1/1 [==============================] - 0s 0s/step - loss: 7.3229
Epoch 726/2000
1/1 [==============================] - 0s 0s/step - loss: 7.3219
Epoch 727/2000
1/1 [==============================]

1/1 [==============================] - 0s 0s/step - loss: 7.2269
Epoch 818/2000
1/1 [==============================] - 0s 0s/step - loss: 7.2259
Epoch 819/2000
1/1 [==============================] - 0s 0s/step - loss: 7.2249
Epoch 820/2000
1/1 [==============================] - 0s 0s/step - loss: 7.2239
Epoch 821/2000
1/1 [==============================] - 0s 0s/step - loss: 7.2229
Epoch 822/2000
1/1 [==============================] - 0s 17ms/step - loss: 7.2219
Epoch 823/2000
1/1 [==============================] - 0s 0s/step - loss: 7.2209
Epoch 824/2000
1/1 [==============================] - 0s 0s/step - loss: 7.2199
Epoch 825/2000
1/1 [==============================] - 0s 0s/step - loss: 7.2189
Epoch 826/2000
1/1 [==============================] - 0s 0s/step - loss: 7.2179
Epoch 827/2000
1/1 [==============================] - 0s 0s/step - loss: 7.2169
Epoch 828/2000
1/1 [==============================] - 0s 17ms/step - loss: 7.2160
Epoch 829/2000
1/1 [==============================]

1/1 [==============================] - 0s 0s/step - loss: 7.1292
Epoch 920/2000
1/1 [==============================] - 0s 0s/step - loss: 7.1283
Epoch 921/2000
1/1 [==============================] - 0s 17ms/step - loss: 7.1274
Epoch 922/2000
1/1 [==============================] - 0s 0s/step - loss: 7.1265
Epoch 923/2000
1/1 [==============================] - 0s 0s/step - loss: 7.1256
Epoch 924/2000
1/1 [==============================] - 0s 0s/step - loss: 7.1247
Epoch 925/2000
1/1 [==============================] - 0s 0s/step - loss: 7.1238
Epoch 926/2000
1/1 [==============================] - 0s 0s/step - loss: 7.1228
Epoch 927/2000
1/1 [==============================] - 0s 16ms/step - loss: 7.1219
Epoch 928/2000
1/1 [==============================] - 0s 0s/step - loss: 7.1210
Epoch 929/2000
1/1 [==============================] - 0s 0s/step - loss: 7.1201
Epoch 930/2000
1/1 [==============================] - 0s 0s/step - loss: 7.1192
Epoch 931/2000
1/1 [==============================]

IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



1/1 [==============================] - 0s 0s/step - loss: 6.8348
Epoch 1299/2000
1/1 [==============================] - 0s 16ms/step - loss: 6.8342
Epoch 1300/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.8335
Epoch 1301/2000
1/1 [==============================] - 0s 0s/step - loss: 6.8329
Epoch 1302/2000
1/1 [==============================] - 0s 0s/step - loss: 6.8322
Epoch 1303/2000
1/1 [==============================] - 0s 0s/step - loss: 6.8316
Epoch 1304/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.8309
Epoch 1305/2000
1/1 [==============================] - 0s 0s/step - loss: 6.8303
Epoch 1306/2000
1/1 [==============================] - 0s 0s/step - loss: 6.8296
Epoch 1307/2000
1/1 [==============================] - 0s 0s/step - loss: 6.8290
Epoch 1308/2000
1/1 [==============================] - 0s 0s/step - loss: 6.8283
Epoch 1309/2000
1/1 [==============================] - 0s 0s/step - loss: 6.8277
Epoch 1310/2000
1/1 [===================

1/1 [==============================] - 0s 0s/step - loss: 6.7723
Epoch 1399/2000
1/1 [==============================] - 0s 0s/step - loss: 6.7717
Epoch 1400/2000
1/1 [==============================] - 0s 0s/step - loss: 6.7711
Epoch 1401/2000
1/1 [==============================] - 0s 0s/step - loss: 6.7705
Epoch 1402/2000
1/1 [==============================] - 0s 14ms/step - loss: 6.7699
Epoch 1403/2000
1/1 [==============================] - 0s 1ms/step - loss: 6.7693
Epoch 1404/2000
1/1 [==============================] - 0s 0s/step - loss: 6.7687
Epoch 1405/2000
1/1 [==============================] - 0s 0s/step - loss: 6.7681
Epoch 1406/2000
1/1 [==============================] - 0s 0s/step - loss: 6.7675
Epoch 1407/2000
1/1 [==============================] - 0s 0s/step - loss: 6.7669
Epoch 1408/2000
1/1 [==============================] - 0s 14ms/step - loss: 6.7664
Epoch 1409/2000
1/1 [==============================] - 0s 0s/step - loss: 6.7658
Epoch 1410/2000
1/1 [==================

1/1 [==============================] - 0s 0s/step - loss: 6.7151
Epoch 1499/2000
1/1 [==============================] - 0s 0s/step - loss: 6.7146
Epoch 1500/2000
1/1 [==============================] - 0s 0s/step - loss: 6.7140
Epoch 1501/2000
1/1 [==============================] - 0s 0s/step - loss: 6.7135
Epoch 1502/2000
1/1 [==============================] - 0s 14ms/step - loss: 6.7129
Epoch 1503/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.7124
Epoch 1504/2000
1/1 [==============================] - 0s 0s/step - loss: 6.7118
Epoch 1505/2000
1/1 [==============================] - 0s 0s/step - loss: 6.7113
Epoch 1506/2000
1/1 [==============================] - 0s 0s/step - loss: 6.7107
Epoch 1507/2000
1/1 [==============================] - 0s 0s/step - loss: 6.7102
Epoch 1508/2000
1/1 [==============================] - 0s 13ms/step - loss: 6.7096
Epoch 1509/2000
1/1 [==============================] - 0s 1ms/step - loss: 6.7091
Epoch 1510/2000
1/1 [=================

1/1 [==============================] - 0s 14ms/step - loss: 6.6628
Epoch 1599/2000
1/1 [==============================] - 0s 1ms/step - loss: 6.6623
Epoch 1600/2000
1/1 [==============================] - 0s 0s/step - loss: 6.6618
Epoch 1601/2000
1/1 [==============================] - 0s 0s/step - loss: 6.6613
Epoch 1602/2000
1/1 [==============================] - 0s 0s/step - loss: 6.6608
Epoch 1603/2000
1/1 [==============================] - 0s 0s/step - loss: 6.6603
Epoch 1604/2000
1/1 [==============================] - 0s 14ms/step - loss: 6.6598
Epoch 1605/2000
1/1 [==============================] - 0s 1ms/step - loss: 6.6593
Epoch 1606/2000
1/1 [==============================] - 0s 0s/step - loss: 6.6588
Epoch 1607/2000
1/1 [==============================] - 0s 0s/step - loss: 6.6583
Epoch 1608/2000
1/1 [==============================] - 0s 0s/step - loss: 6.6578
Epoch 1609/2000
1/1 [==============================] - 0s 0s/step - loss: 6.6573
Epoch 1610/2000
1/1 [=================

1/1 [==============================] - 0s 0s/step - loss: 6.6149
Epoch 1699/2000
1/1 [==============================] - 0s 13ms/step - loss: 6.6144
Epoch 1700/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.6140
Epoch 1701/2000
1/1 [==============================] - 0s 0s/step - loss: 6.6135
Epoch 1702/2000
1/1 [==============================] - 0s 0s/step - loss: 6.6130
Epoch 1703/2000
1/1 [==============================] - 0s 0s/step - loss: 6.6126
Epoch 1704/2000
1/1 [==============================] - 0s 0s/step - loss: 6.6121
Epoch 1705/2000
1/1 [==============================] - 0s 14ms/step - loss: 6.6117
Epoch 1706/2000
1/1 [==============================] - 0s 0s/step - loss: 6.6112
Epoch 1707/2000
1/1 [==============================] - 0s 0s/step - loss: 6.6108
Epoch 1708/2000
1/1 [==============================] - 0s 0s/step - loss: 6.6103
Epoch 1709/2000
1/1 [==============================] - 0s 0s/step - loss: 6.6099
Epoch 1710/2000
1/1 [==================

1/1 [==============================] - 0s 0s/step - loss: 6.5711
Epoch 1799/2000
1/1 [==============================] - 0s 0s/step - loss: 6.5706
Epoch 1800/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.5702
Epoch 1801/2000
1/1 [==============================] - 0s 0s/step - loss: 6.5698
Epoch 1802/2000
1/1 [==============================] - 0s 0s/step - loss: 6.5694
Epoch 1803/2000
1/1 [==============================] - 0s 0s/step - loss: 6.5690
Epoch 1804/2000
1/1 [==============================] - 0s 0s/step - loss: 6.5685
Epoch 1805/2000
1/1 [==============================] - 0s 0s/step - loss: 6.5681
Epoch 1806/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.5677
Epoch 1807/2000
1/1 [==============================] - 0s 0s/step - loss: 6.5673
Epoch 1808/2000
1/1 [==============================] - 0s 0s/step - loss: 6.5669
Epoch 1809/2000
1/1 [==============================] - 0s 0s/step - loss: 6.5665
Epoch 1810/2000
1/1 [=====================

1/1 [==============================] - 0s 0s/step - loss: 6.5310
Epoch 1899/2000
1/1 [==============================] - 0s 0s/step - loss: 6.5306
Epoch 1900/2000
1/1 [==============================] - 0s 13ms/step - loss: 6.5302
Epoch 1901/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.5298
Epoch 1902/2000
1/1 [==============================] - 0s 0s/step - loss: 6.5294
Epoch 1903/2000
1/1 [==============================] - 0s 0s/step - loss: 6.5290
Epoch 1904/2000
1/1 [==============================] - 0s 0s/step - loss: 6.5287
Epoch 1905/2000
1/1 [==============================] - 0s 0s/step - loss: 6.5283
Epoch 1906/2000
1/1 [==============================] - 0s 13ms/step - loss: 6.5279
Epoch 1907/2000
1/1 [==============================] - 0s 0s/step - loss: 6.5275
Epoch 1908/2000
1/1 [==============================] - 0s 0s/step - loss: 6.5272
Epoch 1909/2000
1/1 [==============================] - 0s 0s/step - loss: 6.5268
Epoch 1910/2000
1/1 [==================

1/1 [==============================] - 0s 0s/step - loss: 6.4943
Epoch 1999/2000
1/1 [==============================] - 0s 0s/step - loss: 6.4939
Epoch 2000/2000
1/1 [==============================] - 0s 0s/step - loss: 6.4936


In [8]:
#세 개의 w값 출력하기
tf.model.layers[0].get_weights()
#현 데어터의 오차가 최소화되어지는 w와 b의 찾은 값을 출력

[array([[0.35509124],
        [0.6260291 ],
        [1.034501  ]], dtype=float32),
 array([-0.0043664], dtype=float32)]

In [9]:
tf.model.predict([[60., 70., 80.], [73., 80., 75.]])
#단순회귀분석: 최소의 오차값으로 w의 값을 찾는 것
#예측 데이터로 이미 학습을 시킨 데이터를 집어넣었을 때 정확도가 100%로 나올 것이라는 착각을 할 수 있음 => (정답 152.으로 결과가 나올까?)
# -> 예측 모델은 데이터들 중에서 오차가 최소가 되는 직선 하나를 찾은 것이기 때문에 실제 데이터와의 연관성으로 결과가 나오는 것이 아님.

1/1 [==============================] - 0s 80ms/step


array([[147.88322],
       [153.58719]], dtype=float32)