In [1]:
# 두 개 이상의 분류군으로 구성하고 싶을 때는 softmax라고 부름 (다중 분류)

import tensorflow as tf
import numpy as np

In [2]:
x_raw = [[1, 2, 1, 1],
         [2, 1, 3, 2],
         [3, 1, 3, 4],
         [4, 1, 5, 5],
         [1, 7, 5, 5],
         [1, 2, 5, 6],
         [1, 6, 6, 6],
         [1, 7, 7, 7]]

y_raw = [[0, 0, 1],
         [0, 0, 1],
         [0, 0, 1],
         [0, 1, 0], 
         [0, 1, 0], 
         [0, 1, 0],
         [1, 0, 0],
         [1, 0, 0]] 
#softmax는 분류를 바이너리 이상으로 하고자 할 때, 기존의 sigmoid모델을 여러 개 구성해서 다중 분류에 신경망 구성을 해주면 됐음
# 분류군에 따라서 sigmoid가 활성화됨. 따라서 sigmoid는 활성화 함수라고 불림
# [[0], [0], [1], [1], [1], [2], [2], [2]] 로 알고리즘에 담아주게 되면 숫자로 인식이 돼서 2가 많은 것으로 판단하게 된다.
# 따라서 도출될 값 자리에 1을 넣어주는 형식으로 결과값을 넣어주도록 한다. (결과값이 세개라면 세개의 메모리 공간을 할당해서 분류군에 해당하는 자리에 1을 넣어주면 됨)
# 지금과 같은 데이터로 알고리즘을 실행하게 되면 결과적으로 3개의 결과가 나오게 된다.
# softmax(sigmoid와 encoding으로 내부적 구성)는 0.5이하면 0으로 0.5이상이면 1로 출력을 내보내주게 된다. 

# 원합인코딩방식: 값이 있는 부분만 1로 셋팅하고 나머지 부분을 0으로 매핑하는 것 => 값을 자동으로 생성해줄 수 있도록 사이킷런에서는 인코딕벡터라이저?기능을 제공해주고 있었음

In [3]:
x_data = np.array(x_raw, dtype=np.float32) #리스트로 저장된 데이터들을 배열의 형태로 변환
y_data = np.array(y_raw, dtype=np.float32)

In [4]:
nb_classes = 3 #바이너리가 몇차원으로 분류되어져야 하는지 저장

tf.model = tf.keras.Sequential()

tf.model.add(tf.keras.layers.Dense(input_dim=x_data.shape[1], 
                                   units=nb_classes, 
                                   activation='softmax'))
#(=) tf.model.add(tf.keras.layers.Activation('softmax')) 

In [5]:
tf.model.compile(loss='categorical_crossentropy',
                optimizer=tf.keras.optimizers.SGD(learning_rate=0.1),
                metrics=['accuracy']) #경사하강법중에서 SGD를 활용 
#선형회귀는 mse, 바이너리는 binary_crossentropy, 다중분류는 categorical_crossentropy

tf.model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 15        
                                                                 
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


In [6]:
loss = tf.model.fit(x_data, y_data, epochs=2000)

Epoch 1/2000
1/1 [==============================] - 0s 349ms/step - loss: 2.3101 - accuracy: 0.3750
Epoch 2/2000
1/1 [==============================] - 0s 3ms/step - loss: 1.6572 - accuracy: 0.5000
Epoch 3/2000
1/1 [==============================] - 0s 4ms/step - loss: 1.5158 - accuracy: 0.5000
Epoch 4/2000
1/1 [==============================] - 0s 0s/step - loss: 1.4179 - accuracy: 0.5000
Epoch 5/2000
1/1 [==============================] - 0s 0s/step - loss: 1.3304 - accuracy: 0.5000
Epoch 6/2000
1/1 [==============================] - 0s 0s/step - loss: 1.2518 - accuracy: 0.5000
Epoch 7/2000
1/1 [==============================] - 0s 14ms/step - loss: 1.1823 - accuracy: 0.5000
Epoch 8/2000
1/1 [==============================] - 0s 1ms/step - loss: 1.1220 - accuracy: 0.5000
Epoch 9/2000
1/1 [==============================] - 0s 0s/step - loss: 1.0705 - accuracy: 0.5000
Epoch 10/2000
1/1 [==============================] - 0s 0s/step - loss: 1.0270 - accuracy: 0.5000
Epoch 11/2000
1/1 [==

1/1 [==============================] - 0s 0s/step - loss: 0.6555 - accuracy: 0.6250
Epoch 167/2000
1/1 [==============================] - 0s 0s/step - loss: 0.5968 - accuracy: 0.7500
Epoch 168/2000
1/1 [==============================] - 0s 14ms/step - loss: 0.6541 - accuracy: 0.6250
Epoch 169/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5953 - accuracy: 0.7500
Epoch 170/2000
1/1 [==============================] - 0s 0s/step - loss: 0.6526 - accuracy: 0.6250
Epoch 171/2000
1/1 [==============================] - 0s 0s/step - loss: 0.5937 - accuracy: 0.7500
Epoch 172/2000
1/1 [==============================] - 0s 0s/step - loss: 0.6511 - accuracy: 0.6250
Epoch 173/2000
1/1 [==============================] - 0s 14ms/step - loss: 0.5922 - accuracy: 0.7500
Epoch 174/2000
1/1 [==============================] - 0s 0s/step - loss: 0.6497 - accuracy: 0.6250
Epoch 175/2000
1/1 [==============================] - 0s 0s/step - loss: 0.5907 - accuracy: 0.7500
Epoch 176/2000
1/1 [

1/1 [==============================] - 0s 0s/step - loss: 0.5584 - accuracy: 0.7500
Epoch 331/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5016 - accuracy: 0.7500
Epoch 332/2000
1/1 [==============================] - 0s 0s/step - loss: 0.5574 - accuracy: 0.7500
Epoch 333/2000
1/1 [==============================] - 0s 0s/step - loss: 0.5007 - accuracy: 0.7500
Epoch 334/2000
1/1 [==============================] - 0s 0s/step - loss: 0.5563 - accuracy: 0.7500
Epoch 335/2000
1/1 [==============================] - 0s 0s/step - loss: 0.4998 - accuracy: 0.7500
Epoch 336/2000
1/1 [==============================] - 0s 849us/step - loss: 0.5553 - accuracy: 0.7500
Epoch 337/2000
1/1 [==============================] - 0s 0s/step - loss: 0.4989 - accuracy: 0.7500
Epoch 338/2000
1/1 [==============================] - 0s 0s/step - loss: 0.5543 - accuracy: 0.7500
Epoch 339/2000
1/1 [==============================] - 0s 0s/step - loss: 0.4979 - accuracy: 0.7500
Epoch 340/2000
1/1 [=

1/1 [==============================] - 0s 2ms/step - loss: 0.4790 - accuracy: 0.8750
Epoch 495/2000
1/1 [==============================] - 0s 0s/step - loss: 0.4336 - accuracy: 0.7500
Epoch 496/2000
1/1 [==============================] - 0s 0s/step - loss: 0.4781 - accuracy: 0.8750
Epoch 497/2000
1/1 [==============================] - 0s 0s/step - loss: 0.4329 - accuracy: 0.7500
Epoch 498/2000
1/1 [==============================] - 0s 14ms/step - loss: 0.4771 - accuracy: 0.8750
Epoch 499/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4321 - accuracy: 0.7500
Epoch 500/2000
1/1 [==============================] - 0s 0s/step - loss: 0.4762 - accuracy: 0.8750
Epoch 501/2000
1/1 [==============================] - 0s 0s/step - loss: 0.4313 - accuracy: 0.7500
Epoch 502/2000
1/1 [==============================] - 0s 0s/step - loss: 0.4753 - accuracy: 0.8750
Epoch 503/2000
1/1 [==============================] - 0s 14ms/step - loss: 0.4306 - accuracy: 0.7500
Epoch 504/2000
1/1 

1/1 [==============================] - 0s 0s/step - loss: 0.4035 - accuracy: 0.8750
Epoch 659/2000
1/1 [==============================] - 0s 0s/step - loss: 0.3739 - accuracy: 0.8750
Epoch 660/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4026 - accuracy: 0.8750
Epoch 661/2000
1/1 [==============================] - 0s 0s/step - loss: 0.3732 - accuracy: 0.8750
Epoch 662/2000
1/1 [==============================] - 0s 0s/step - loss: 0.4017 - accuracy: 0.8750
Epoch 663/2000
1/1 [==============================] - 0s 0s/step - loss: 0.3725 - accuracy: 0.8750
Epoch 664/2000
1/1 [==============================] - 0s 14ms/step - loss: 0.4008 - accuracy: 0.8750
Epoch 665/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.3718 - accuracy: 0.8750
Epoch 666/2000
1/1 [==============================] - 0s 0s/step - loss: 0.3999 - accuracy: 0.8750
Epoch 667/2000
1/1 [==============================] - 0s 0s/step - loss: 0.3711 - accuracy: 0.8750
Epoch 668/2000
1/1 [=

1/1 [==============================] - 0s 0s/step - loss: 0.3288 - accuracy: 0.8750
Epoch 823/2000
1/1 [==============================] - 0s 0s/step - loss: 0.3157 - accuracy: 0.8750
Epoch 824/2000
1/1 [==============================] - 0s 0s/step - loss: 0.3279 - accuracy: 0.8750
Epoch 825/2000
1/1 [==============================] - 0s 15ms/step - loss: 0.3150 - accuracy: 0.8750
Epoch 826/2000
1/1 [==============================] - 0s 0s/step - loss: 0.3270 - accuracy: 0.8750
Epoch 827/2000
1/1 [==============================] - 0s 0s/step - loss: 0.3143 - accuracy: 0.8750
Epoch 828/2000
1/1 [==============================] - 0s 0s/step - loss: 0.3261 - accuracy: 0.8750
Epoch 829/2000
1/1 [==============================] - 0s 0s/step - loss: 0.3136 - accuracy: 0.8750
Epoch 830/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3252 - accuracy: 0.8750
Epoch 831/2000
1/1 [==============================] - 0s 0s/step - loss: 0.3129 - accuracy: 0.8750
Epoch 832/2000
1/1 [==

1/1 [==============================] - 0s 0s/step - loss: 0.2583 - accuracy: 1.0000
Epoch 987/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2569 - accuracy: 1.0000
Epoch 988/2000
1/1 [==============================] - 0s 0s/step - loss: 0.2576 - accuracy: 1.0000
Epoch 989/2000
1/1 [==============================] - 0s 0s/step - loss: 0.2563 - accuracy: 1.0000
Epoch 990/2000
1/1 [==============================] - 0s 0s/step - loss: 0.2569 - accuracy: 1.0000
Epoch 991/2000
1/1 [==============================] - 0s 0s/step - loss: 0.2557 - accuracy: 1.0000
Epoch 992/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2562 - accuracy: 1.0000
Epoch 993/2000
1/1 [==============================] - 0s 0s/step - loss: 0.2550 - accuracy: 1.0000
Epoch 994/2000
1/1 [==============================] - 0s 0s/step - loss: 0.2555 - accuracy: 1.0000
Epoch 995/2000
1/1 [==============================] - 0s 0s/step - loss: 0.2544 - accuracy: 1.0000
Epoch 996/2000
1/1 [===

1/1 [==============================] - 0s 0s/step - loss: 0.2285 - accuracy: 1.0000
Epoch 1149/2000
1/1 [==============================] - 0s 0s/step - loss: 0.2284 - accuracy: 1.0000
Epoch 1150/2000
1/1 [==============================] - 0s 0s/step - loss: 0.2283 - accuracy: 1.0000
Epoch 1151/2000
1/1 [==============================] - 0s 0s/step - loss: 0.2282 - accuracy: 1.0000
Epoch 1152/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2281 - accuracy: 1.0000
Epoch 1153/2000
1/1 [==============================] - 0s 0s/step - loss: 0.2280 - accuracy: 1.0000
Epoch 1154/2000
1/1 [==============================] - 0s 0s/step - loss: 0.2279 - accuracy: 1.0000
Epoch 1155/2000
1/1 [==============================] - 0s 0s/step - loss: 0.2277 - accuracy: 1.0000
Epoch 1156/2000
1/1 [==============================] - 0s 13ms/step - loss: 0.2276 - accuracy: 1.0000
Epoch 1157/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2275 - accuracy: 1.0000
Epoch 1158/2

1/1 [==============================] - 0s 0s/step - loss: 0.2114 - accuracy: 1.0000
Epoch 1311/2000
1/1 [==============================] - 0s 0s/step - loss: 0.2113 - accuracy: 1.0000
Epoch 1312/2000
1/1 [==============================] - 0s 0s/step - loss: 0.2112 - accuracy: 1.0000
Epoch 1313/2000
1/1 [==============================] - 0s 13ms/step - loss: 0.2111 - accuracy: 1.0000
Epoch 1314/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2110 - accuracy: 1.0000
Epoch 1315/2000
1/1 [==============================] - 0s 0s/step - loss: 0.2109 - accuracy: 1.0000
Epoch 1316/2000
1/1 [==============================] - 0s 0s/step - loss: 0.2108 - accuracy: 1.0000
Epoch 1317/2000
1/1 [==============================] - 0s 14ms/step - loss: 0.2107 - accuracy: 1.0000
Epoch 1318/2000
1/1 [==============================] - 0s 304us/step - loss: 0.2106 - accuracy: 1.0000
Epoch 1319/2000
1/1 [==============================] - 0s 0s/step - loss: 0.2105 - accuracy: 1.0000
Epoch 13

1/1 [==============================] - 0s 0s/step - loss: 0.1966 - accuracy: 1.0000
Epoch 1473/2000
1/1 [==============================] - 0s 0s/step - loss: 0.1965 - accuracy: 1.0000
Epoch 1474/2000
1/1 [==============================] - 0s 14ms/step - loss: 0.1964 - accuracy: 1.0000
Epoch 1475/2000
1/1 [==============================] - 0s 268us/step - loss: 0.1963 - accuracy: 1.0000
Epoch 1476/2000
1/1 [==============================] - 0s 0s/step - loss: 0.1962 - accuracy: 1.0000
Epoch 1477/2000
1/1 [==============================] - 0s 0s/step - loss: 0.1961 - accuracy: 1.0000
Epoch 1478/2000
1/1 [==============================] - 0s 0s/step - loss: 0.1961 - accuracy: 1.0000
Epoch 1479/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1960 - accuracy: 1.0000
Epoch 1480/2000
1/1 [==============================] - 0s 0s/step - loss: 0.1959 - accuracy: 1.0000
Epoch 1481/2000
1/1 [==============================] - 0s 0s/step - loss: 0.1958 - accuracy: 1.0000
Epoch 1482

1/1 [==============================] - 0s 2ms/step - loss: 0.1836 - accuracy: 1.0000
Epoch 1635/2000
1/1 [==============================] - 0s 0s/step - loss: 0.1835 - accuracy: 1.0000
Epoch 1636/2000
1/1 [==============================] - 0s 0s/step - loss: 0.1835 - accuracy: 1.0000
Epoch 1637/2000
1/1 [==============================] - 0s 0s/step - loss: 0.1834 - accuracy: 1.0000
Epoch 1638/2000
1/1 [==============================] - 0s 13ms/step - loss: 0.1833 - accuracy: 1.0000
Epoch 1639/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.1832 - accuracy: 1.0000
Epoch 1640/2000
1/1 [==============================] - 0s 0s/step - loss: 0.1832 - accuracy: 1.0000
Epoch 1641/2000
1/1 [==============================] - 0s 0s/step - loss: 0.1831 - accuracy: 1.0000
Epoch 1642/2000
1/1 [==============================] - 0s 0s/step - loss: 0.1830 - accuracy: 1.0000
Epoch 1643/2000
1/1 [==============================] - 0s 14ms/step - loss: 0.1829 - accuracy: 1.0000
Epoch 1644

1/1 [==============================] - 0s 1ms/step - loss: 0.1722 - accuracy: 1.0000
Epoch 1797/2000
1/1 [==============================] - 0s 0s/step - loss: 0.1721 - accuracy: 1.0000
Epoch 1798/2000
1/1 [==============================] - 0s 0s/step - loss: 0.1721 - accuracy: 1.0000
Epoch 1799/2000
1/1 [==============================] - 0s 0s/step - loss: 0.1720 - accuracy: 1.0000
Epoch 1800/2000
1/1 [==============================] - 0s 14ms/step - loss: 0.1719 - accuracy: 1.0000
Epoch 1801/2000
1/1 [==============================] - 0s 829us/step - loss: 0.1719 - accuracy: 1.0000
Epoch 1802/2000
1/1 [==============================] - 0s 0s/step - loss: 0.1718 - accuracy: 1.0000
Epoch 1803/2000
1/1 [==============================] - 0s 0s/step - loss: 0.1717 - accuracy: 1.0000
Epoch 1804/2000
1/1 [==============================] - 0s 0s/step - loss: 0.1717 - accuracy: 1.0000
Epoch 1805/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1716 - accuracy: 1.0000
Epoch 180

1/1 [==============================] - 0s 0s/step - loss: 0.1621 - accuracy: 1.0000
Epoch 1959/2000
1/1 [==============================] - 0s 0s/step - loss: 0.1620 - accuracy: 1.0000
Epoch 1960/2000
1/1 [==============================] - 0s 14ms/step - loss: 0.1619 - accuracy: 1.0000
Epoch 1961/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.1619 - accuracy: 1.0000
Epoch 1962/2000
1/1 [==============================] - 0s 0s/step - loss: 0.1618 - accuracy: 1.0000
Epoch 1963/2000
1/1 [==============================] - 0s 0s/step - loss: 0.1618 - accuracy: 1.0000
Epoch 1964/2000
1/1 [==============================] - 0s 0s/step - loss: 0.1617 - accuracy: 1.0000
Epoch 1965/2000
1/1 [==============================] - 0s 15ms/step - loss: 0.1616 - accuracy: 1.0000
Epoch 1966/2000
1/1 [==============================] - 0s 0s/step - loss: 0.1616 - accuracy: 1.0000
Epoch 1967/2000
1/1 [==============================] - 0s 0s/step - loss: 0.1615 - accuracy: 1.0000
Epoch 1968/

In [7]:
y_prob = tf.model.predict(np.array([[1, 2, 3, 2]]))
y_prob

#가장 큰 값을 1의 의미로 삼는다. 1의 의미로 삼아도 0.5보다 작음.
#지금 현재 예측률이 낮기 때문에 결과로 봤을 때 비율값이 sigmoid가 0.5에 근접하지만 넘지 않게 나온 것임.

1/1 [==============================] - 0s 54ms/step


array([[0.3121755, 0.2270672, 0.4607573]], dtype=float32)

In [8]:
y_prob.argmax(axis=1)
#최대값을 찾는데 열을 기준으로 하나의 데이터에서 찾도록 함 -> 인덱스값을 반환해줌

array([2], dtype=int64)

In [10]:
y_prob = tf.model.predict(np.array([[1, 11, 7, 9],
                                    [1, 3, 4, 3],
                                    [1, 1, 0, 1]]))
y_prob

1/1 [==============================] - 0s 17ms/step


array([[8.4969774e-03, 9.9149305e-01, 1.0042998e-05],
       [8.2253999e-01, 1.5995206e-01, 1.7508043e-02],
       [1.6684846e-08, 3.7293302e-04, 9.9962699e-01]], dtype=float32)

In [11]:
y_prob.argmax(axis=1)

array([1, 0, 2], dtype=int64)